config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  post 'sessions/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[create new show]
  root to: 'users#new'
  resources :events, only: %i[create new show index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :events_registrators, foreign_key: :attended_event_id
  has_many :attendees, through: :events_registrators

  scope :future, -> { where('time >= ?', DateTime.now).order(time: :desc) }
  scope :past, -> { where('time < ?', DateTime.now).order(time: :desc) }
end

app/models/events_registrator.rb
class EventsRegistrator < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :events_registrators, foreign_key: :attendee_id
  has_many :attended_events, through: :events_registrators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/sessions/new' unless current_user
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  def new
    @event = Event.new
    @attendee = EventsRegistrator.new
  end

  def index
    @events = current_user.events
    @creator = current_user.username
    @future = @events.future
    @past = @events.past
  end

  def create
    @users = User.all
    @event = current_user.events.build(event_params.except(:attendees))

    @event.creator_id = session[:user_id]

    if @event.save
      flash.notice = "Event '#{@event.title}' Created!"
      event_params.slice(:attendees).values.each do |x|
        x.each do |y|
          if y.empty?
          else
            user = @users.find(y.to_i)
            @event.attendees << user
          end
        end
      end
      redirect_to event_path(@event)

    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendee = @event.attendees
  end

  private

  def event_users_params
    params.require(:events_registrator).permit(:attendee_id, :attended_event_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by_username(params[:username])
    # If the user exists AND the password entered is correct.
    if @user
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      # If user's login doesn't work, send them back to the login form.
      redirect_to '/sessions/new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/sessions/new'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash.notice = "User '#{@user.username}' Created!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @events = @user.events
    @attended_events = @user.attended_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def event_params
    params.require(:event).permit(:title, :description, :time, attendees: [])
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_params
    params.require(:user).permit(:username)
  end
end

app/views/events/index.html.erb
<h1>Events#index</h1>
<h1>The all events that this specific user has created</h1>
<p>The creator is: <b><%= @creator %></p></b>
<div>
  <% @future.each do |future| %>
  <p>The upcoming events: <%= future.title %></p>
  <p><%= future.time %></p>
<% end %>
</div>

<div>
  <% @past.each do |past| %>
  <p>The past events:  <%= past.title %></p>
  <p><%= past.time %></p>
<% end %>
</div>
<%= link_to 'back', new_event_path %>

app/views/events/new.html.erb
<h1>Events#new</h1>
<div>
  <%= form_for @event do |event| %>
    <div>
      <%= event.label :title %>
      <div>
        <%= event.text_field :title, placeholder: "Enter the title" %>
      </div>
    </div>
    <div>
      <%= event.label :description %>
      <div>
        <%= event.text_field :description, placeholder: "Enter the description" %>
      </div>
    </div>
    <div>
      <div class="field">
        <%= event.label :time %>
        <%= event.date_field :time %>
      </div>
      <div class="field">
        <%= event.label "Guest List" %>
        <%= event.collection_check_boxes :attendees, User.all, :id, :username do |user| %>
          <div class="collection-check-box" style='display:flex'>
            <%= user.check_box %>
            <%= user.label %>
          </div>
        <% end %>
        </div>
    </div>
    <div>
      <%= event.submit 'Add' %>
    </div>
  <% end %>
</div>
<p id="notice"><%= flash[:notice] %></p>

app/views/events/show.html.erb
<h1>Events#show</h1>

<div class="Events">
  <p>The creator is: <b><%= @event.creator.username %></p></b>
  <p>The title is: <b><%= @event.title %></p></b>
  <p>The Description is: <b><%= @event.description %></p></b>
   <p>The time is: <%= @event.time %></p>

  <p>The attendees are: </p>
  <% @attendee.each do |attendee| %>
    <p><%= attendee.username %></p>
<% end %>
</div>

<%= link_to 'back', new_event_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>PrivateEvents2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
  <div class="Links">
    <%= link_to "LogIn", sessions_new_path %>
    <%= link_to "Register", new_user_path %>
    <%= link_to "New Event", new_event_path %>
    <%= link_to "All user events", events_path %>
    <%= link_to "Log out", sessions_destroy_path %>
  </div>
  
</body>

</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p id="notice"><%= flash[:notice] %></p>
<div>
  <%= form_with(model: @user, url: users_path, method: 'post') do |user| %>
    <div>
      <%= user.label :username %>
      <div>
        <%= user.text_field :username, placeholder: "Enter username" %>
      </div>
    </div>
    <div>
      <%= user.submit 'Add' %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<div>
  <p>The user is : <%= @user.username %></p>
  <p>The events the user has created:</p>
  <% @events.each do |event|%>
  <div>
    
    <%= event.title %>
  </div>
  <% end %>
</div>

<div>
  <b><p>The events the user has or will be attended:</p></b>
  <% @attended_events.each do |event|%>
  <div>
    <% if event.time > DateTime.now %>
    <p>The future events: <%= event.title %></p>
  <% else %>
  <p>The past events: <%= event.title %></p>
  <% end %>
  </div>
  <% end %>
</div>


<%= link_to 'back', new_user_path %>